import { type Metadata } from 'next';
import { type ReactNode } from 'react';
import './globals.css';
import AppLayout from '@/layouts/app-layout';
import { ThemeProvider } from '@/contexts/theme-provider';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
};

export default function RootLayout({
    children
}: Readonly<{
    children: ReactNode;
}>) {
    return (
        <html lang="en" className="scroll-smooth" suppressHydrationWarning>
            <body className="antialiased">
                <ThemeProvider>
                    <AppLayout>{children}</AppLayout>
                </ThemeProvider>
            </body>
        </html>
    );
}
